spring:
  redis:
    cluster:
      nodes:
        - 192.168.171.127:7000
        - 192.168.171.127:7001
        - 192.168.171.127:7002
        - 192.168.171.127:7003
        - 192.168.171.127:7004
        - 192.168.171.127:7005
      max-redirects: 2
    password:
    database: 0
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: 30 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接

