server:
  port: 8082
  servlet:
    context-path: /user

spring:
  application:
    name: cloud-user-service
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.171.127:3306/study?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.ddup.user.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  server:
    enable-self-preservation: true
