server:
  port: 8081
  servlet:
    context-path: /user

spring:
  application:
    name: cloud-user-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  server:
    enable-self-preservation: true

