server:
  port: 8081
  servlet:
    context-path: /user

spring:
  application:
    name: cloud-user-service
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/tyrcb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  server:
    enable-self-preservation: true
logging:
  level:
    com.ddup.cloud: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%p] %highlight(%C:%L) : %m%n"