server:
  port: 8089
  servlet:
    context-path: /consumer

spring:
  application:
    name: consumer-service
#  redis:
#    host: 192.168.171.127
#    port: 6379
#    password: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    server:
      enable-self-preservation: true
feign:
  hystrix:
    enabled: true #在Feign中开启Hystrix。如果处理自身的容错就开启。开启方式与生产端不一样。
  client:
    config:
      default:
        connectTimeout: 2000  # 指定Feign客户端连接提供者的超时时限   取决于网络环境
        readTimeout: 2000   # 指定Feign客户端从请求到获取到提供者给出的响应的超时时限  取决于业务逻辑运算时间
  compression:
    request:
      enabled: true
      mime-types: text/xml, application/xml
      min-request-size: 2048
    response:
      enabled: true


#设置超时降级时间（spring-cloud-starter-openfeign中的HystrixCommandProperties默认为1000毫秒）
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000


#设置hystrix日志级别是DEBUG
logging:
  level:
    com.netflix.hystrix: debug
    com.ddup.cloud: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%p] %highlight(%C:%L) : %m%n"